- hosts: nxos
  connection: local
  gather_facts: no
  tasks:
    - name: Test reachability to a few different public IPs using mgmt vrf
      nxos_ping:
        dest: "{{ item }}"
        vrf: management
      with_items:
        - 8.8.8.8
        - 168.95.1.1
      register: result

    - name: Print result
      debug:
        msg: "{{ result }}"
