- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
    - name: Run show version on remote devices
      nxos_command:
        commands:
            - command: show version
              output: json
      register: result

    - name: Print result
      debug:
        msg: "{{ result }}"
